spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/file-storage
    username: root
    password: ymsyms
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 9005

storage:
    base:
      path: D:/TestEnv/file-storage/
      url: http://localhost:9005/file/storage/
